version: "3.9"

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: dfir-backend
    restart: "no"   # disable auto-restart while debugging
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/postgres"
    volumes:
      - ./apps/backend/app:/app/app

  db:
    image: postgres:14
    container_name: dfir-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
